import * as vscode from "vscode";
import * as fs from "fs";
import * as path from "path";
import colorKeysData from "./vscode-color-keys.json";

// Generated by scripts/generate-color-keys.mjs from the canonical VS Code
// theme-color docs. Refresh via `npm run update-color-keys`.
export const VALID_COLOR_KEYS: ReadonlySet<string> = new Set(colorKeysData.colors);
export const COLOR_KEYS_META = {
  source: colorKeysData.source,
  fetchedAt: colorKeysData.fetchedAt,
  count: colorKeysData.count,
  sections: colorKeysData.sections as Record<string, string[]>,
};

export interface ThemeColors {
  [key: string]: string;
}

export interface TokenColorSetting {
  foreground?: string;
  fontStyle?: string;
}

export interface TokenColor {
  name: string;
  scope: string | string[];
  settings: TokenColorSetting;
}

export interface ThemeData {
  colors: ThemeColors;
  tokenColors: TokenColor[];
}

export interface PresetInfo {
  name: string;
  description?: string;
  builtIn?: boolean;
}

export interface Preset extends PresetInfo {
  theme: ThemeData;
}

export class ThemeEngine {
  private presetsDir: string;
  private builtInPresetsDir: string;
  private statePath: string;
  private basePath: string;
  private _activePresetName: string | null = null;

  constructor(private context: vscode.ExtensionContext) {
    this.presetsDir = path.join(context.globalStorageUri.fsPath, "presets");
    this.builtInPresetsDir = path.join(context.extensionPath, "presets");
    this.statePath = path.join(context.globalStorageUri.fsPath, "state.json");
    this.basePath = path.join(context.extensionPath, "themes", "everytheme-color-theme.json");
    fs.mkdirSync(this.presetsDir, { recursive: true });
    this._activePresetName = this.loadState().activePreset;
  }

  /** Base theme shipped with the extension. These are the colors VS Code
   *  actually renders when no override is set for a given key. */
  getBaseTheme(): ThemeData {
    if (!fs.existsSync(this.basePath)) {
      return { colors: {}, tokenColors: [] };
    }
    const raw = JSON.parse(fs.readFileSync(this.basePath, "utf-8"));
    return {
      colors: raw.colors ?? {},
      tokenColors: raw.tokenColors ?? [],
    };
  }

  /** The currently rendered theme = base + current overrides. This is what
   *  the user actually sees, and is what the LLM needs when computing tweaks
   *  like "lighten editor background by 8%" against an unset key. */
  getEffectiveTheme(): ThemeData {
    const base = this.getBaseTheme();
    const overrides = this.getCurrentTheme();
    const colors: ThemeColors = { ...base.colors, ...overrides.colors };
    const byName = new Map<string, TokenColor>();
    for (const tc of base.tokenColors) byName.set(tc.name, tc);
    for (const tc of overrides.tokenColors) byName.set(tc.name, tc);
    return { colors, tokenColors: [...byName.values()] };
  }

  get activePresetName(): string | null {
    return this._activePresetName;
  }

  private loadState(): { activePreset: string | null } {
    if (fs.existsSync(this.statePath)) {
      return JSON.parse(fs.readFileSync(this.statePath, "utf-8"));
    }
    return { activePreset: null };
  }

  private saveState(): void {
    fs.writeFileSync(
      this.statePath,
      JSON.stringify({ activePreset: this._activePresetName }),
      "utf-8"
    );
  }

  /** Read the current effective colors from VS Code settings overrides */
  getCurrentTheme(): ThemeData {
    const config = vscode.workspace.getConfiguration();
    const colors = config.get<ThemeColors>("workbench.colorCustomizations") ?? {};
    const tokenConfig = config.get<{ textMateRules?: TokenColor[] }>(
      "editor.tokenColorCustomizations"
    ) ?? {};
    return {
      colors,
      tokenColors: tokenConfig.textMateRules ?? [],
    };
  }

  /** Summary of what the user is actually seeing — base theme merged with
   *  current overrides. This is the context the LLM needs to reason about
   *  tweaks. Override counts are reported separately so the model knows
   *  what's been touched vs. what it's inheriting from the base theme. */
  getColorSummary(): {
    activePreset: string | null;
    editorColors: ThemeColors;
    tokenColors: Array<{ name: string; scope: string | string[] } & TokenColorSetting>;
    overrideColorCount: number;
    overrideTokenCount: number;
  } {
    const effective = this.getEffectiveTheme();
    const overrides = this.getCurrentTheme();
    return {
      activePreset: this._activePresetName,
      editorColors: effective.colors,
      tokenColors: effective.tokenColors.map((tc) => ({
        name: tc.name,
        scope: tc.scope,
        ...tc.settings,
      })),
      overrideColorCount: Object.keys(overrides.colors).length,
      overrideTokenCount: overrides.tokenColors.length,
    };
  }

  /** Update workbench/editor colors. Returns which keys were applied,
   *  which were rejected as unknown VS Code color ids, and which had
   *  invalid hex values. */
  async setColors(colors: ThemeColors): Promise<{
    changed: string[];
    unknownKeys: string[];
    invalidHex: string[];
  }> {
    const config = vscode.workspace.getConfiguration();
    const current = config.get<ThemeColors>("workbench.colorCustomizations") ?? {};
    const changed: string[] = [];
    const unknownKeys: string[] = [];
    const invalidHex: string[] = [];

    for (const [key, value] of Object.entries(colors)) {
      if (!VALID_COLOR_KEYS.has(key)) {
        unknownKeys.push(key);
        continue;
      }
      if (!isValidHexColor(value)) {
        invalidHex.push(`${key}=${value}`);
        continue;
      }
      current[key] = value;
      changed.push(key);
    }

    if (changed.length > 0) {
      await config.update(
        "workbench.colorCustomizations",
        current,
        vscode.ConfigurationTarget.Global
      );
      this.autoSaveActivePreset();
    }
    return { changed, unknownKeys, invalidHex };
  }

  /** Update token colors by name */
  async setTokenColors(
    updates: Array<{ name: string; scope?: string | string[]; foreground?: string; fontStyle?: string }>
  ): Promise<string[]> {
    const config = vscode.workspace.getConfiguration();
    const tokenConfig = config.get<{ textMateRules?: TokenColor[] }>(
      "editor.tokenColorCustomizations"
    ) ?? {};
    const rules = tokenConfig.textMateRules ?? [];
    const changed: string[] = [];

    for (const update of updates) {
      const existing = rules.find(
        (tc) => tc.name.toLowerCase() === update.name.toLowerCase()
      );
      if (existing) {
        if (update.foreground && isValidHexColor(update.foreground)) {
          existing.settings.foreground = update.foreground;
        }
        if (update.fontStyle !== undefined) {
          existing.settings.fontStyle = update.fontStyle;
        }
        changed.push(existing.name);
      } else {
        // Add new rule — need at least a scope
        const scope = update.scope ?? update.name.toLowerCase();
        const settings: TokenColorSetting = {};
        if (update.foreground && isValidHexColor(update.foreground)) {
          settings.foreground = update.foreground;
        }
        if (update.fontStyle !== undefined) {
          settings.fontStyle = update.fontStyle;
        }
        rules.push({ name: update.name, scope, settings });
        changed.push(update.name);
      }
    }

    await config.update(
      "editor.tokenColorCustomizations",
      { ...tokenConfig, textMateRules: rules },
      vscode.ConfigurationTarget.Global
    );
    this.autoSaveActivePreset();
    return changed;
  }

  /** Auto-save to the active preset if one exists. Saves the *effective*
   *  theme (base + overrides) so the preset is a complete, self-contained
   *  colorset — loading it later doesn't depend on the base theme still
   *  being present or unchanged. */
  private autoSaveActivePreset(): void {
    if (this._activePresetName) {
      const theme = this.getEffectiveTheme();
      const existing = this.getPreset(this._activePresetName);
      const preset: Preset = {
        name: this._activePresetName,
        description: existing?.description,
        theme,
      };
      fs.writeFileSync(
        this.presetPath(this._activePresetName),
        JSON.stringify(preset, null, 2),
        "utf-8"
      );
    }
  }

  /** Reset theme — clear all color overrides */
  async resetTheme(): Promise<void> {
    const config = vscode.workspace.getConfiguration();
    await config.update(
      "workbench.colorCustomizations",
      undefined,
      vscode.ConfigurationTarget.Global
    );
    await config.update(
      "editor.tokenColorCustomizations",
      undefined,
      vscode.ConfigurationTarget.Global
    );
    this._activePresetName = null;
    this.saveState();
  }

  // --- Preset management ---

  private safeName(name: string): string {
    return name.replace(/[^a-zA-Z0-9_-]/g, "_");
  }

  private presetPath(name: string): string {
    return path.join(this.presetsDir, `${this.safeName(name)}.json`);
  }

  private builtInPresetPath(name: string): string {
    return path.join(this.builtInPresetsDir, `${this.safeName(name)}.json`);
  }

  /** True if the preset name has no user copy and only exists as a built-in. */
  isBuiltInPreset(name: string): boolean {
    return !fs.existsSync(this.presetPath(name)) && fs.existsSync(this.builtInPresetPath(name));
  }

  listPresets(): PresetInfo[] {
    const seen = new Map<string, PresetInfo>();
    const readDir = (dir: string, builtIn: boolean) => {
      if (!fs.existsSync(dir)) return;
      for (const f of fs.readdirSync(dir).filter((f) => f.endsWith(".json"))) {
        try {
          const raw = JSON.parse(fs.readFileSync(path.join(dir, f), "utf-8"));
          if (!seen.has(raw.name)) {
            seen.set(raw.name, { name: raw.name, description: raw.description, builtIn });
          }
        } catch {
          // skip malformed preset files
        }
      }
    };
    // User presets take precedence over built-ins of the same name.
    readDir(this.presetsDir, false);
    readDir(this.builtInPresetsDir, true);
    return [...seen.values()];
  }

  getPreset(name: string): Preset | undefined {
    const userPath = this.presetPath(name);
    if (fs.existsSync(userPath)) {
      return JSON.parse(fs.readFileSync(userPath, "utf-8"));
    }
    const builtInPath = this.builtInPresetPath(name);
    if (fs.existsSync(builtInPath)) {
      return JSON.parse(fs.readFileSync(builtInPath, "utf-8"));
    }
    return undefined;
  }

  savePreset(name: string, description?: string): void {
    const theme = this.getEffectiveTheme();
    const preset: Preset = { name, description, theme };
    fs.writeFileSync(this.presetPath(name), JSON.stringify(preset, null, 2), "utf-8");
    this._activePresetName = name;
    this.saveState();
  }

  deletePreset(name: string): boolean {
    const p = this.presetPath(name);
    if (!fs.existsSync(p)) {
      return false;
    }
    fs.unlinkSync(p);
    return true;
  }

  async loadPreset(name: string): Promise<boolean> {
    const preset = this.getPreset(name);
    if (!preset) {
      return false;
    }
    await this.applyTheme(preset.theme);
    this._activePresetName = name;
    this.saveState();
    return true;
  }

  clonePreset(sourceName: string, newName: string, newDescription?: string): boolean {
    const source = this.getPreset(sourceName);
    if (!source) {
      return false;
    }
    const clone: Preset = {
      name: newName,
      description: newDescription ?? source.description,
      theme: JSON.parse(JSON.stringify(source.theme)),
    };
    fs.writeFileSync(this.presetPath(newName), JSON.stringify(clone, null, 2), "utf-8");
    return true;
  }

  renamePreset(oldName: string, newName: string): boolean {
    if (this.isBuiltInPreset(oldName)) {
      // Built-ins ship with the extension and can't be renamed; clone instead.
      return false;
    }
    const preset = this.getPreset(oldName);
    if (!preset) {
      return false;
    }
    preset.name = newName;
    fs.writeFileSync(this.presetPath(newName), JSON.stringify(preset, null, 2), "utf-8");
    fs.unlinkSync(this.presetPath(oldName));
    if (this._activePresetName === oldName) {
      this._activePresetName = newName;
      this.saveState();
    }
    return true;
  }

  /** Apply a full theme by writing both color and token customizations */
  private async applyTheme(theme: ThemeData): Promise<void> {
    const config = vscode.workspace.getConfiguration();
    await config.update(
      "workbench.colorCustomizations",
      Object.keys(theme.colors).length > 0 ? theme.colors : undefined,
      vscode.ConfigurationTarget.Global
    );
    await config.update(
      "editor.tokenColorCustomizations",
      theme.tokenColors.length > 0 ? { textMateRules: theme.tokenColors } : undefined,
      vscode.ConfigurationTarget.Global
    );
  }
}

function isValidHexColor(color: string): boolean {
  return /^#[0-9A-Fa-f]{6,8}$/.test(color);
}
